name: CI/CD Salao de Beleza

# 1. Gatilho: A esteira roda toda vez que houver um push na branch main
on:
  push:
    branches: [ "main" ]

jobs:
  # ==========================================
  # JOB 1: VALIDAÇÃO (Testes, Build e Sonar)
  # ==========================================
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Obrigatório para o Sonar analisar o histórico do Git

    - name: Setup Java JDK 17 (Requisito do Sonar)
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Instalar SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Iniciar Analise do SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner begin /k:"GabrielThales_AgendamentoSalao" /o:"gabrielthales" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

    - name: Restaurar dependencias
      run: dotnet restore AgendamentoSalao.slnx

    - name: Compilar a aplicacao (Build)
      run: dotnet build AgendamentoSalao.slnx --no-restore --configuration Release

    - name: Executar Testes Unitarios e Gerar Relatorio de Cobertura

      run: dotnet test AgendamentoSalao.slnx --no-build --configuration Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Finalizar Analise do SonarCloud e Enviar Dados
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  # ==========================================
  # JOB 2: EMPACOTAMENTO (Docker)
  # ==========================================
  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v4

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir e Enviar Imagem Docker (Build & Push)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/api-salao-beleza:latest

  # ==========================================
  # JOB 3: Terraform -> Ansible -> DEPLOY (Docker) -> AWS
  # ==========================================      
  deploy:
      needs: docker-build-push # So roda se a imagem for enviada com sucesso
      runs-on: ubuntu-latest
      steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Descobrir o IP do GitHub Runner
        id: ip
        run: echo "RUNNER_IP=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

      - name: Terraform Apply
        working-directory: ./infra
        run: |
          terraform init
          terraform apply -var="ssh_ip=${{ env.RUNNER_IP }}" -auto-approve

      - name: Obter IP da Instancia
        id: get_ip
        working-directory: ./infra
        run: echo "EC2_IP=$(terraform output -raw ip_publico)" >> $GITHUB_ENV
    
      - name: Preparar Chave SSH e Rodar Ansible
        env:
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 400 key.pem
          # Espera a maquina ligar completamente
          sleep 30 
          ansible-playbook -i "$EC2_IP," ./infra/playbook.yml \
            --private-key key.pem \
            -u ubuntu \
            --extra-vars "docker_user=${{ secrets.DOCKER_USERNAME }}" \
            --ssh-common-args='-o StrictHostKeyChecking=no'